#  Spacje i odst?py s? tutaj MEGA wa?ne inaczej nie zadzia?a
  spring:
    h2.console:
      enabled: true
      path: '/console'
    datasource:
      url: 'jdbc:h2:file:./todo-db'
    jpa:
      hibernate:
        ddl-auto: validate
#        ddl -> data definition language. Gdy dodałem @Column w encji aplikacja się dzięki temu nie uruchamia
#       [Schema-validation: missing column [deadline] in table [tasks] ].
#       Trzeba dodać migracje SQL w db.migration.