#  Spacje i odst?py s? tutaj wyj?tkowo wa?ne inaczej nie zadzia?a
  spring:
   h2.console:
    enabled: true
    path: '/console'
   datasource:
    url: 'jdbc:h2:file:./todo-db'
  task.allowMultipleTasksFromTempate: false
  jpa:
    hibernate:
      ddl-auto: create-drop
